export const ROUTES = {
  HOME: '/',
  BLOG: '/blog',
  CONTACT: '/contact',
  FEEDBACK: '/feedback',
  SIP: '/sip',
  SIP_DAILY: '/sip-daily',
  SIP_WEEKLY: '/sip-weekly',
  SIP_MONTHLY: '/sip',
  SIP_QUARTERLY: '/sip-quarterly',
  SIP_YEARLY: '/sip-yearly',
  STEP_UP_SIP: '/step-up-sip',
  EMI: '/emi',
  EMI_HOME_LOAN: '/emi/home-loan',
  EMI_CAR_LOAN: '/emi/car-loan',
  EMI_PERSONAL_LOAN: '/emi/personal-loan',
  EMI_EDU_LOAN: '/emi/edu-loan',
  NEW_TAX_REGIME_2024_25: '/new-regime-income-tax-calculator/2024-25',
  NEW_TAX_REGIME_2025_26: '/new-regime-income-tax-calculator/2025-26',
  OLD_TAX_REGIME: '/old-regime-income-tax-calculator',
  OLD_VS_NEW_REGIME: '/old-vs-new-regime-income-tax-calculator',
  SALARY: '/salary-calculator',
} as const; 